In [ ]:
import numpy as np

In [7]:
zeros_array = np.zeros(10)
zeros_array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
fives_array = np.full(10, 5)
fives_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
int_array = np.arange(10, 51)
int_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
even_int_array = np.arange(10, 51, 2)
even_int_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
random_numbers = np.random.rand(25)
random_numbers

array([0.57507357, 0.54896016, 0.22926543, 0.37239498, 0.13335959,
       0.98524933, 0.32512624, 0.28883349, 0.93883287, 0.0348199 ,
       0.03654888, 0.96511346, 0.01266119, 0.55235356, 0.41355078,
       0.02624582, 0.6429261 , 0.84659546, 0.37970429, 0.25422631,
       0.02329262, 0.98479205, 0.47017134, 0.68013419, 0.7918541 ])